[package]
name = "gen"
version = "0.1.0"
authors = ["Jihyun Yu <yjh0502@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.31"
argh = { git = "https://github.com/google/argh.git" }
env_logger = "0.7.1"
log = "0.4.11"
rayon = "1.3.1"
serde = "1.0.114"
serde_derive = "1.0.114"
serde-gen = { git = "https://github.com/yjh0502/serde-gen" }
serde_yaml = "0.8"
yaml-rust = "0.4"
stopwatch = "0.0.7"
walkdir = "2.3.1"
ordslice = "0.3.0"
bytesize = "1"
rand = "0.7"
glob = "0.3"
parse = { path = "../parse" }
